// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagement.DbContexts;

#nullable disable

namespace WarehouseManagement.Migrations
{
    [DbContext(typeof(WarehouseManagmentContext))]
    [Migration("20230110102623_seedingWarehouses")]
    partial class seedingWarehouses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WarehouseManagement.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WarehouseManagement.Entities.BillDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<Guid>("managerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<Guid>("warehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("702b0a47-e7cd-42ca-bed6-e08b66abb653"),
                            Name = "Ahmad"
                        },
                        new
                        {
                            Id = new Guid("927ef47d-2231-4218-a8a8-f570b12c7fde"),
                            Name = "Ali"
                        },
                        new
                        {
                            Id = new Guid("d0f1d718-05c8-48d6-a4d0-62a06f2d0d29"),
                            Name = "Yamen"
                        },
                        new
                        {
                            Id = new Guid("a90e41b6-be95-4382-97cc-4f6970b1978c"),
                            Name = "Mohannad"
                        },
                        new
                        {
                            Id = new Guid("90515313-fb47-4ab4-bec1-9303c7661e48"),
                            Name = "Abdo"
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87bb64c6-1eb0-4e26-b245-afc6359147d5"),
                            Name = "Sugar",
                            Price = 5000.0
                        },
                        new
                        {
                            Id = new Guid("9e9c1db5-afe3-4948-915f-34806db86462"),
                            Name = "Salt",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = new Guid("81b13ee0-2ca3-4f2a-b9d5-70f06a4f29cb"),
                            Name = "Indomi",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = new Guid("9a66da83-ec29-4f75-8b8d-a36d543c17b5"),
                            Name = "Coffe",
                            Price = 55000.0
                        },
                        new
                        {
                            Id = new Guid("d558dc08-c5a8-4dcc-ad35-00c170bb0330"),
                            Name = "Tee",
                            Price = 60000.0
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Product_Bill", b =>
                {
                    b.Property<Guid>("Product_Warehouse_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Product_Warehouse_Id", "BillDetailsId");

                    b.HasIndex("BillDetailsId");

                    b.ToTable("Products_Bills");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Product_Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("Products_Warehouses");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("MainWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MainWarehouseId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1330cde5-971d-4727-989a-efff06576c86"),
                            Address = "Alzahraa",
                            ManagerId = new Guid("702b0a47-e7cd-42ca-bed6-e08b66abb653"),
                            Name = "Alzahraa"
                        },
                        new
                        {
                            Id = new Guid("734f2c3c-0a2a-4860-a6c6-27c013b6aa21"),
                            Address = "Mohafaza",
                            ManagerId = new Guid("927ef47d-2231-4218-a8a8-f570b12c7fde"),
                            Name = "Mohafaza"
                        },
                        new
                        {
                            Id = new Guid("86bb2b95-d023-4390-8dc1-2d27da8a8a15"),
                            Address = "Mogambo",
                            ManagerId = new Guid("d0f1d718-05c8-48d6-a4d0-62a06f2d0d29"),
                            Name = "Mogambo"
                        },
                        new
                        {
                            Id = new Guid("c22d0d3e-4e42-4a3b-a930-f628c14b874d"),
                            Address = "Andalos",
                            ManagerId = new Guid("a90e41b6-be95-4382-97cc-4f6970b1978c"),
                            Name = "Andalos"
                        },
                        new
                        {
                            Id = new Guid("5af29802-9a62-42e9-bb5e-b3459cb81f40"),
                            Address = "Hamdania",
                            ManagerId = new Guid("90515313-fb47-4ab4-bec1-9303c7661e48"),
                            Name = "Hamdania"
                        },
                        new
                        {
                            Id = new Guid("fcc58645-f4cd-4700-a667-fec39323fded"),
                            Address = "Alzahraa",
                            MainWarehouseId = new Guid("1330cde5-971d-4727-989a-efff06576c86"),
                            ManagerId = new Guid("702b0a47-e7cd-42ca-bed6-e08b66abb653"),
                            Name = "Alzahraa.1"
                        },
                        new
                        {
                            Id = new Guid("3daf5dd6-dbb4-44d8-88ac-15c65a6741d4"),
                            Address = "Mohafaza",
                            MainWarehouseId = new Guid("734f2c3c-0a2a-4860-a6c6-27c013b6aa21"),
                            ManagerId = new Guid("927ef47d-2231-4218-a8a8-f570b12c7fde"),
                            Name = "Mohafaza.1"
                        },
                        new
                        {
                            Id = new Guid("4dd38fd3-8fcc-4de5-b56c-169785e1586f"),
                            Address = "Mogambo",
                            MainWarehouseId = new Guid("86bb2b95-d023-4390-8dc1-2d27da8a8a15"),
                            ManagerId = new Guid("d0f1d718-05c8-48d6-a4d0-62a06f2d0d29"),
                            Name = "Mogambo.1"
                        },
                        new
                        {
                            Id = new Guid("11ec5b78-7e2b-41c2-ae9f-5634a1105887"),
                            Address = "Andalos",
                            MainWarehouseId = new Guid("c22d0d3e-4e42-4a3b-a930-f628c14b874d"),
                            ManagerId = new Guid("a90e41b6-be95-4382-97cc-4f6970b1978c"),
                            Name = "Andalos.1"
                        },
                        new
                        {
                            Id = new Guid("e24e4c78-aa68-4f6e-9749-56da8bb6f67a"),
                            Address = "Hamdania",
                            MainWarehouseId = new Guid("5af29802-9a62-42e9-bb5e-b3459cb81f40"),
                            ManagerId = new Guid("90515313-fb47-4ab4-bec1-9303c7661e48"),
                            Name = "Hamdania.1"
                        },
                        new
                        {
                            Id = new Guid("879eb9b1-1bfb-4fd5-96e2-9a4bbc500c29"),
                            Address = "Alzahraa",
                            MainWarehouseId = new Guid("1330cde5-971d-4727-989a-efff06576c86"),
                            ManagerId = new Guid("702b0a47-e7cd-42ca-bed6-e08b66abb653"),
                            Name = "Alzahraa.2"
                        },
                        new
                        {
                            Id = new Guid("f27a7dd1-b44a-423f-9a84-2462a0f2ad48"),
                            Address = "Andalos",
                            MainWarehouseId = new Guid("c22d0d3e-4e42-4a3b-a930-f628c14b874d"),
                            ManagerId = new Guid("a90e41b6-be95-4382-97cc-4f6970b1978c"),
                            Name = "Andalos.2"
                        },
                        new
                        {
                            Id = new Guid("53965e59-5ad4-4d1b-bf98-b743fb1d8681"),
                            Address = "Andalos",
                            MainWarehouseId = new Guid("c22d0d3e-4e42-4a3b-a930-f628c14b874d"),
                            ManagerId = new Guid("a90e41b6-be95-4382-97cc-4f6970b1978c"),
                            Name = "Andalos.3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WarehouseManagement.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WarehouseManagement.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WarehouseManagement.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseManagement.Auth.ApplicationUser", b =>
                {
                    b.OwnsMany("WarehouseManagement.Auth.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicationUserId", "Id");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Product_Bill", b =>
                {
                    b.HasOne("WarehouseManagement.Entities.BillDetails", "BillDetail")
                        .WithMany("Product_Bills")
                        .HasForeignKey("BillDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Entities.Product_Warehouse", "Product_Warehouse")
                        .WithMany("Product_Bills")
                        .HasForeignKey("Product_Warehouse_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillDetail");

                    b.Navigation("Product_Warehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Product_Warehouse", b =>
                {
                    b.HasOne("WarehouseManagement.Entities.Product", "Product")
                        .WithMany("Product_Warehouses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Entities.Warehouse", "Warehouse")
                        .WithMany("Product_Warehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Warehouse", b =>
                {
                    b.HasOne("WarehouseManagement.Entities.Warehouse", "MainWarehouse")
                        .WithMany()
                        .HasForeignKey("MainWarehouseId");

                    b.HasOne("WarehouseManagement.Entities.Manager", "Manager")
                        .WithMany("Warehouses")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainWarehouse");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.BillDetails", b =>
                {
                    b.Navigation("Product_Bills");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Manager", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Product", b =>
                {
                    b.Navigation("Product_Warehouses");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Product_Warehouse", b =>
                {
                    b.Navigation("Product_Bills");
                });

            modelBuilder.Entity("WarehouseManagement.Entities.Warehouse", b =>
                {
                    b.Navigation("Product_Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
